version: '3'
networks:
  mang:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: "nginx_${APP_NAME}"
    ports:
      - "8080:80"
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mang

  php:
    image: php:7.1-fpm
    container_name: "php_${APP_NAME}"
    ports:
      - "9000:9000"
    networks:
      - mang
    volumes:
      - ./src:/var/www/html
